// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVLo6t8odWtAcDR4TBxPwKZsPfNQ7hvfY',
    appId: '1:531782026308:web:f58d690e9217bd98ef6811',
    messagingSenderId: '531782026308',
    projectId: 'pulseai-a0548',
    authDomain: 'pulseai-a0548.firebaseapp.com',
    storageBucket: 'pulseai-a0548.firebasestorage.app',
    measurementId: 'G-EDZMCR35J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoHY9t9FYAV9pPElAAF3iXxO_2gJwKYAI',
    appId: '1:531782026308:android:b7ebbe25a9bff574ef6811',
    messagingSenderId: '531782026308',
    projectId: 'pulseai-a0548',
    storageBucket: 'pulseai-a0548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhmZlIGlDTs-OVZwfHNvjHivBoEDjQnwU',
    appId: '1:531782026308:ios:a69211542de8a3faef6811',
    messagingSenderId: '531782026308',
    projectId: 'pulseai-a0548',
    storageBucket: 'pulseai-a0548.firebasestorage.app',
    iosBundleId: 'com.example.pulseai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhmZlIGlDTs-OVZwfHNvjHivBoEDjQnwU',
    appId: '1:531782026308:ios:a69211542de8a3faef6811',
    messagingSenderId: '531782026308',
    projectId: 'pulseai-a0548',
    storageBucket: 'pulseai-a0548.firebasestorage.app',
    iosBundleId: 'com.example.pulseai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVLo6t8odWtAcDR4TBxPwKZsPfNQ7hvfY',
    appId: '1:531782026308:web:07177c3c67949fe8ef6811',
    messagingSenderId: '531782026308',
    projectId: 'pulseai-a0548',
    authDomain: 'pulseai-a0548.firebaseapp.com',
    storageBucket: 'pulseai-a0548.firebasestorage.app',
    measurementId: 'G-HZRS30QBEW',
  );
}
