// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJbpXPl_yscqgtr2OesVfU0JF-0ewOlss',
    appId: '1:1034033111503:web:aa107f21f2e11553d7f2ba',
    messagingSenderId: '1034033111503',
    projectId: 'pulseai-org',
    authDomain: 'pulseai-org.firebaseapp.com',
    storageBucket: 'pulseai-org.firebasestorage.app',
    measurementId: 'G-D03Y2MM08G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_o7Vruvl04xug48K89fKIYODYKPIuRg',
    appId: '1:1034033111503:android:9598cbfd727be78bd7f2ba',
    messagingSenderId: '1034033111503',
    projectId: 'pulseai-org',
    storageBucket: 'pulseai-org.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3GR1OvEpLUFiU3NXqHuP9cCxaMpGKhC4',
    appId: '1:1034033111503:ios:1fb35e4d65928e3ad7f2ba',
    messagingSenderId: '1034033111503',
    projectId: 'pulseai-org',
    storageBucket: 'pulseai-org.firebasestorage.app',
    androidClientId: '1034033111503-rah3vdc08vu1es993l9oido2lap1g0kp.apps.googleusercontent.com',
    iosClientId: '1034033111503-t0mhvurn0blad18akhe4nn83kqlqqoof.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulseai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3GR1OvEpLUFiU3NXqHuP9cCxaMpGKhC4',
    appId: '1:1034033111503:ios:1fb35e4d65928e3ad7f2ba',
    messagingSenderId: '1034033111503',
    projectId: 'pulseai-org',
    storageBucket: 'pulseai-org.firebasestorage.app',
    androidClientId: '1034033111503-rah3vdc08vu1es993l9oido2lap1g0kp.apps.googleusercontent.com',
    iosClientId: '1034033111503-t0mhvurn0blad18akhe4nn83kqlqqoof.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulseai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJbpXPl_yscqgtr2OesVfU0JF-0ewOlss',
    appId: '1:1034033111503:web:82467d0321d73f00d7f2ba',
    messagingSenderId: '1034033111503',
    projectId: 'pulseai-org',
    authDomain: 'pulseai-org.firebaseapp.com',
    storageBucket: 'pulseai-org.firebasestorage.app',
    measurementId: 'G-RZW0VWKR19',
  );

}